name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud-Init
        run: |
          cloud-init -v || exit 0
          sudo apt-get install --no-install-recommends -y cloud-init

      # Add your build and test steps here

      - name: Run Cloud-Init
        run: |
          cloud-init -v
